gitlab:
  image: 'gitlab/gitlab-ce:12.10.3-ce.0'
  container_name: gitlab
  restart: always
  hostname: 'gitlab.agro.pub'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      #Host and port 
      external_url 'http://gitlab.agro.pub'
      gitlab_rails['gitlab_ssh_host'] = '59.110.139.173'
      gitlab_rails['time_zone'] = 'Asia/Shanghai'
      gitlab_rails['gitlab_shell_ssh_port'] = 8022
      # Mail setting
      gitlab_rails['gitlab_email_enabled'] = true
      gitlab_rails['gitlab_email_from'] = '329083231@qq.com'
      gitlab_rails['gitlab_email_display_name'] = 'gitlab.agro.pub'
      gitlab_rails['gitlab_email_reply_to'] = 'xxxx@yyyyyyy.com'
      gitlab_rails['gitlab_email_subject_suffix'] = 'Gitlab'
      # Smtp setting
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.qq.com"
      gitlab_rails['smtp_port'] = 465
      gitlab_rails['smtp_user_name'] = "329083231@qq.com"
      gitlab_rails['smtp_password'] = "jcrwdbkultncbjch"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = true
      gitlab_rails['gitlab_email_from'] = '329083231@qq.com'
      gitlab_rails['smtp_domain'] = "qq.com"
  ports:
    - '8082:80'
    - '8443:443'
    - '8022:22'
  volumes:
    - '/opt/gitlab/config:/etc/gitlab'
    - '/opt/gitlab/logs:/var/log/gitlab'
    - '/opt/gitlab/data:/var/opt/gitlab'